# Generated by Django 4.2 on 2024-01-25 10:19

from django.db import migrations, models
import django_jalali.db.models
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان خبر')),
                ('content', models.TextField(verbose_name='متن خبر')),
                ('author', models.CharField(blank=True, max_length=250, null=True, verbose_name='نویسنده خبر')),
                ('news_img', models.ImageField(upload_to=shop.models.news_image_path, verbose_name='تصویر')),
                ('create_date', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('update_date', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
        ),
    ]
