# Generated by Django 4.2 on 2024-01-31 17:01

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_cat', models.CharField(choices=[('hc', 'صنایع دستی'), ('fs', 'مواد غذایی'), ('ha', 'لوازم خانگی'), ('rt', 'تفریح و گردشگری')], max_length=2, verbose_name='گروه')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'خبر', 'verbose_name_plural': 'اخبار'},
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='create_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
    ]
