# Generated by Django 4.2 on 2024-01-31 18:10

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productcategory_alter_newsletter_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان محصول')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('product_img', models.ImageField(upload_to=shop.models.products_image_path, verbose_name='تصویر')),
                ('status', models.CharField(choices=[('avb', 'موجود'), ('uav', 'ناموجود')], max_length=3, verbose_name='وضعیت')),
                ('create_date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_date', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.productcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
