# Generated by Django 4.2 on 2024-01-31 18:20

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='update_date',
            field=django_jalali.db.models.jDateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان آخرین ویرایش'),
        ),
    ]
