# Generated by Django 4.2 on 2024-02-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_newsletter_update_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='staff_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد موجودی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت موجودی'),
        ),
    ]
