# Generated by Django 4.2 on 2024-02-05 11:57

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد')),
                ('date_added', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='محصول')),
                ('user_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ipaddress', verbose_name='آی پی کاربر')),
            ],
        ),
    ]
