# Generated by Django 4.2 on 2024-02-09 10:10

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shoppingcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=150, verbose_name='آدرس ایمیل')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('send_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ناریخ ارسال')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'تماس با ما',
            },
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'محصول سبد خرید', 'verbose_name_plural': 'سبد خرید'},
        ),
    ]
