# Generated by Django 4.2 on 2024-02-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_contactus_alter_shoppingcart_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user_ip',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user_uuid',
            field=models.CharField(default='', verbose_name='شناسه کاربر'),
        ),
        migrations.DeleteModel(
            name='IPAddress',
        ),
    ]
