# Generated by Django 4.2 on 2024-02-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_shoppingcart_user_ip_shoppingcart_user_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='user_uuid',
            field=models.CharField(default='', max_length=40, verbose_name='شناسه کاربر'),
        ),
    ]
